webhooks:
  webhooks_enabled:
    client: true
    default: false
  webhooks_registered_events:
    client: true
    default: 'topic_created|post_created'
    type: list
  webhooks_url_format:
    client: true
    default: 'https://example.com/forum-hook/%{event_name}/'
  webhooks_verify_ssl:
    client: true
    default: true
  webhooks_include_api_key:
    client: true
    default: true
  webhooks_logging_enabled:
    client: true
    default: false
  webhooks_site_url:
    client: true
    default: 'https://discourse.mysite.com/forum/'
  webhooks_discourse_api_key:
    client: true
    default: ''
  webhooks_discourse_api_username:
    client: true
    default: ''
  webhooks_new_user_notification:
    client: true
    default: true
